{% set name = "pnpm-licenses" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/@quantco/pnpm-licenses/-/pnpm-licenses-{{ version }}.tgz
  sha256: 7c8708fd5a757936e47304868645fbca4113a04ca50241395c717066ef7b8089

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - pnpm >=8.6.12
  run:
    - nodejs

test:
  commands:
    - pnpm-licenses --version
    - test -d $PREFIX/lib/node_modules/@quantco/pnpm-licenses  # [unix]
    - if not exist %LIBRARY_INC%\share\pnpm-licenses\node_modules\.bin\pnpm-licenses.cmd exit 1  # [win]

about:
  home: https://github.com/Quantco/pnpm-licenses
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Generate third party license disclaimers in pnpm-based projects

extra:
  recipe-maintainers:
    - JannikWibkerQC
    - pavelzw
    - xhochy
